### ISSUE TITLE
How to use http with the listener

### ISSUE THREAD

**Issue by SaberCodeSmith** [adwait-thattey/keycloak-event-listener-spi#1]
Hello, i've read you article [here](https://dev.to/adwaitthattey/building-an-event-listener-spi-plugin-for-keycloak-2044). and it work great. But i want to instead showing the logs to insert them in my DB.

What i've tried is adding mongo-java-driver dependency first, then built with 'mvn clean install', then i followed you instructions untill then end.

So when an event occur keycloak gives me an errorException that com.mongo can't be found. I think there's something that i should do when i built with maven. Any ideas ?

After waisting several hours, i've decided to use an api call, so i've added a dependency called OkHttp for that. But it gives again the same error that OkHttp can't be found. 

Please help !

**Comment by adwait-thattey** [comment]
Did you add all dependencies to pom.xml?

**Comment by adwait-thattey** [comment]
Hello
Closing this issue as no update
Please let me know if still active
