### ISSUE TITLE
Result into custom jndi lookup

### ISSUE THREAD

**Issue by JeffreyTan1001** [adwait-thattey/keycloak-event-listener-spi#2]
How to save response into custom database by jndi lookup?

**Comment by adwait-thattey** [comment]
I haven't used JNDI, but I suppose you can do it in `onEvent` method.
https://github.com/adwait-thattey/keycloak-event-listener-spi/blob/master/sample_event_listener/src/main/java/com/coderdude/sampleeventlistenerprovider/provider/SampleEventListenerProvider.java#L18

**Comment by adwait-thattey** [comment]
Hello
Closing this issue as no update
Please let me know if still active
